steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/blockchain-backend'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
images:
  - 'gcr.io/$PROJECT_ID/blockchain-backend'
